# Generated by Django 6.0.4 on 2026-04-23 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
