# Generated by Django 6.0.4 on 2026-04-23 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_office_code'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='performancerecord',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='indicator',
            name='target_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='performancerecord',
            name='year',
            field=models.IntegerField(default=2024),
        ),
        migrations.AlterField(
            model_name='performancerecord',
            name='quarter',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='performancerecord',
            unique_together={('indicator', 'quarter', 'year')},
        ),
    ]
