# Generated by Django 6.0.4 on 2026-04-23 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_performancerecord_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performancerecord',
            name='year',
            field=models.IntegerField(default=2026),
        ),
    ]
