# Generated by Django 6.0.4 on 2026-05-13 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_activitylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('scope', models.CharField(choices=[('global', 'All offices'), ('offices', 'Selected offices only')], default='global', max_length=20)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('offices', models.ManyToManyField(blank=True, related_name='announcements', to='core.office')),
            ],
            options={
                'ordering': ['sort_order', '-created_at', '-id'],
            },
        ),
    ]
